### ISSUE TITLE
Children having multiple parents

### ISSUE THREAD

**Issue by bigdaddy75** [etrepat/baum#147]
Hello. Is it possible to support a hierarchy with children under multiple parents? I am testing out your package and appreciate how it alleviates the complex query statements needed. I assume I will need a pivot table or duplicate named rows (I would like to avoid).

This is for a categories table. My thought, using a mundane category like "Celebrity" which can belong to a number of parent categories:

Parent 1
   Celebrity
   Sports
   ...
Parent 2
   Celebrity
   ...

**Comment by etrepat** [comment]
This is not possible in Baum because each node under a nested set implementation, must maintain two indices with data relating to its nesting level and its relation to its parent/s and children, thus having children under multiple parent violates a core principle of the algorithm.

I don't say it is not possible at all, just that using a Nested Set implementation (like Baum) will get you into trouble pretty soon for this specific use case.
